compatibility_date = "2023-12-01"

[build]
command = "npm run build"
[build.environment]
NODE_VERSION = "20.17.0"

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
dir = ".vercel/output/functions"
main = "_worker.js"

[site]
bucket = ".vercel/output/static"
entry-point = "_worker.js" 